### ISSUE TITLE
SimPEG(emg3d) - ToDo's

### ISSUE THREAD

**Issue by sgkang** [emsig/emg3d#210]
When performing the order test and adjoint test, I realized that the `optimize.gradient` function only works
when the data are located at the exact locations where the fields are defined (e.g. ex at x-edge locations).
Had a quick look how the backward propagation has implemented, and I am suspicious `def _get_rfield`. 
This should be an exact adjoint (or hermition operation of the data projection).

**Comment by prisae** [comment]
The `optimize.gradient` works for data at any location, they do not have to be on the edges.

Each receiver acts as a source with the residual (measured data - computed data) as strength in the back-propagation. The "residual-source" is then defined in the same way as a normal source. This means that its strength is interpolated to the neighbouring edges using tri-linear adjoint interpolation (see `emg3d.fields._dipole_vector` in the dev-1.0 version).

For this by default the point receiver is turned into a 1m long dipole. This is something that could be modified.

Best to have a call once, maybe I understand you wrong.

**Comment by prisae** [comment]
(Potentially linked to #132 )

**Comment by prisae** [comment]
I renamed the issue @sgkang , so we can use if for anything cropping up with regards to `SimPEG(emg3d)` until its functional!

As promised, I will look into the parallel `jvec` in early June.

**Comment by prisae** [comment]
I classified it also as a bug, to make it higher priority. First testing has shown that there is indeed a problem.

The `dev-solver` branch has in the Simulation-class a new keyword:
```
Simulation(
    ...=...,
    receiver_interpolation='cubic'
)
```
`'cubic'` is the default (status quo), but it can be set to `'linear'`. It will then be respected in all calls to get_receiver within simulations and within optimize.

Eventually we probably want to expand this, and enable one interpolation method for the result (cubic), and one for the gradient (linear).

**Comment by prisae** [comment]
Status quo with cubic interpolation of the receiver response:
![cubic-interp-rec](https://user-images.githubusercontent.com/8020943/120390006-76435180-c32d-11eb-98ec-5a5fe6d0e8ee.png)

When using linear interpolation of the receiver response:
![linear-interp-rec](https://user-images.githubusercontent.com/8020943/120390007-76dbe800-c32d-11eb-8ff6-eebe8542f231.png)

This poses some more questions
- The response we obtain at receivers is potentially less precise (because we interpolate linearly), but the gradient is better -- what does that mean?
- We will have to rethink the gradient for the magnetic receivers. Because they are measured at a point, but afterwards modelled with a loop, so the difference there is even bigger than in the electric case...

**Comment by prisae** [comment]
Things to do:
- [ ] #228 
- [ ] #229 
- [ ] Integrate @sgkang 's `jvec`, `_jvec`, `_get_vec_fields`; for this, I would like to generalize:
  - `compute`, `get_efield`, `get_h_field`, `_get_efield`
  - `_bcompute`, `_get_rfield`, `_get_bfields`, (`get_source_field`?)
  - make `_store_responses` flexible
  - `get(type, source, frequency)`-fct
  
  Many of these are duplicates with only slightly different behaviour. Better abstraction should make it possible to combine them all.

**Comment by prisae** [comment]
All this should be implemented by now.
